version: "3.7"

services:
    backend:
        build: .
        deploy:
            replicas: 3
        volumes:
            - ./:/code
    proxy:
        image: nginx:1.21.4-alpine
        restart: always
        build:
          context: ./nginx
        ports:
            - "8080:80"
        volumes:
          - ./nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
          - backend
